[package]
name = "symphra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
annotate-snippets.workspace = true
thiserror.workspace = true
indicatif = "0.18"
symphra-engine.workspace = true
symphra-export.workspace = true
