[package]
name = "symphra-lsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
symphra-compiler.workspace = true
symphra-syntax.workspace = true
tokio.workspace = true
tower-lsp-server.workspace = true

[dev-dependencies]
serde_json.workspace = true
