use crate::SourceSpan;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TokenKind {
    Identifier,
    Integer,
    Decimal,
    String,
    Project,
    Song,
    Seed,
    SampleRate,
    Output,
    Tempo,
    Meter,
    Key,
    Instrument,
    Sample,
    Choose,
    Weight,
    Sampled,
    Sampler,
    Source,
    Root,
    Pack,
    Rhythm,
    Resolution,
    Hit,
    Track,
    Role,
    Volume,
    Play,
    TriggerWith,
    Gate,
    Transpose,
    Gain,
    Repeat,
    Reverse,
    Pan,
    Pattern,
    Arrangement,
    With,
    Sequence,
    Steps,
    Degree,
    Octave,
    Note,
    Chord,
    Rest,
    For,
    Velocity,
    LeftBrace,
    RightBrace,
    Equal,
    Slash,
    Plus,
    Minus,
    PipeGreater,
    Percent,
    Eof,
}

impl TokenKind {
    pub(crate) fn keyword(text: &str) -> Option<Self> {
        Some(match text {
            "project" => Self::Project,
            "song" => Self::Song,
            "seed" => Self::Seed,
            "sample_rate" => Self::SampleRate,
            "output" => Self::Output,
            "tempo" => Self::Tempo,
            "meter" => Self::Meter,
            "key" => Self::Key,
            "instrument" => Self::Instrument,
            "sample" => Self::Sample,
            "choose" => Self::Choose,
            "weight" => Self::Weight,
            "sampled" => Self::Sampled,
            "sampler" => Self::Sampler,
            "source" => Self::Source,
            "root" => Self::Root,
            "pack" => Self::Pack,
            "rhythm" => Self::Rhythm,
            "resolution" => Self::Resolution,
            "hit" => Self::Hit,
            "track" => Self::Track,
            "role" => Self::Role,
            "volume" => Self::Volume,
            "play" => Self::Play,
            "trigger_with" => Self::TriggerWith,
            "gate" => Self::Gate,
            "transpose" => Self::Transpose,
            "gain" => Self::Gain,
            "repeat" => Self::Repeat,
            "reverse" => Self::Reverse,
            "pan" => Self::Pan,
            "pattern" => Self::Pattern,
            "arrangement" => Self::Arrangement,
            "with" => Self::With,
            "sequence" => Self::Sequence,
            "steps" => Self::Steps,
            "degree" => Self::Degree,
            "octave" => Self::Octave,
            "note" => Self::Note,
            "chord" => Self::Chord,
            "rest" => Self::Rest,
            "for" => Self::For,
            "velocity" => Self::Velocity,
            _ => return None,
        })
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub text: String,
    pub span: SourceSpan,
}
