use crate::SourceSpan;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TokenKind {
    Identifier,
    Integer,
    Decimal,
    String,
    Project,
    Song,
    Seed,
    SampleRate,
    Output,
    Tempo,
    Meter,
    Key,
    Instrument,
    Sample,
    Choose,
    Weight,
    Sampled,
    Sampler,
    DrumMachine,
    Source,
    Root,
    Pack,
    Bank,
    Drum,
    Rhythm,
    Resolution,
    Hit,
    Track,
    Role,
    Volume,
    Layer,
    Use,
    Play,
    TriggerWith,
    Gate,
    Transpose,
    Gain,
    Repeat,
    Reverse,
    Pan,
    Alternate,
    Chance,
    Speed,
    Retrigger,
    ChooseSample,
    At,
    Pattern,
    Arrangement,
    With,
    Sequence,
    Steps,
    Degree,
    Octave,
    Note,
    Chord,
    Rest,
    For,
    Velocity,
    Bar,
    Effect,
    Delay,
    Mix,
    Time,
    Feedback,
    Filter,
    Cutoff,
    Resonance,
    Reverb,
    Size,
    Automate,
    Lfo,
    Range,
    Rate,
    Cycles,
    Section,
    Bars,
    Parallel,
    Exact,
    Master,
    Limiter,
    Ceiling,
    LeftBrace,
    RightBrace,
    Equal,
    Slash,
    Plus,
    Minus,
    PipeGreater,
    Percent,
    DotDot,
    Colon,
    LeftParen,
    RightParen,
    Comma,
    Eof,
}

impl TokenKind {
    pub(crate) fn keyword(text: &str) -> Option<Self> {
        Some(match text {
            "project" => Self::Project,
            "song" => Self::Song,
            "seed" => Self::Seed,
            "sample_rate" => Self::SampleRate,
            "output" => Self::Output,
            "tempo" => Self::Tempo,
            "meter" => Self::Meter,
            "key" => Self::Key,
            "instrument" => Self::Instrument,
            "sample" => Self::Sample,
            "choose" => Self::Choose,
            "weight" => Self::Weight,
            "sampled" => Self::Sampled,
            "sampler" => Self::Sampler,
            "drum_machine" => Self::DrumMachine,
            "source" => Self::Source,
            "root" => Self::Root,
            "pack" => Self::Pack,
            "bank" => Self::Bank,
            "drum" => Self::Drum,
            "rhythm" => Self::Rhythm,
            "resolution" => Self::Resolution,
            "hit" => Self::Hit,
            "track" => Self::Track,
            "role" => Self::Role,
            "volume" => Self::Volume,
            "layer" => Self::Layer,
            "use" => Self::Use,
            "play" => Self::Play,
            "trigger_with" => Self::TriggerWith,
            "gate" => Self::Gate,
            "transpose" => Self::Transpose,
            "gain" => Self::Gain,
            "repeat" => Self::Repeat,
            "reverse" => Self::Reverse,
            "pan" => Self::Pan,
            "alternate" => Self::Alternate,
            "chance" => Self::Chance,
            "speed" => Self::Speed,
            "retrigger" => Self::Retrigger,
            "choose_sample" => Self::ChooseSample,
            "at" => Self::At,
            "pattern" => Self::Pattern,
            "arrangement" => Self::Arrangement,
            "with" => Self::With,
            "sequence" => Self::Sequence,
            "steps" => Self::Steps,
            "degree" => Self::Degree,
            "octave" => Self::Octave,
            "note" => Self::Note,
            "chord" => Self::Chord,
            "rest" => Self::Rest,
            "for" => Self::For,
            "velocity" => Self::Velocity,
            "bar" => Self::Bar,
            "effect" => Self::Effect,
            "delay" => Self::Delay,
            "mix" => Self::Mix,
            "time" => Self::Time,
            "feedback" => Self::Feedback,
            "filter" => Self::Filter,
            "cutoff" => Self::Cutoff,
            "resonance" => Self::Resonance,
            "reverb" => Self::Reverb,
            "size" => Self::Size,
            "automate" => Self::Automate,
            "lfo" => Self::Lfo,
            "range" => Self::Range,
            "rate" => Self::Rate,
            "cycles" => Self::Cycles,
            "section" => Self::Section,
            "bars" => Self::Bars,
            "parallel" => Self::Parallel,
            "exact" => Self::Exact,
            "master" => Self::Master,
            "limiter" => Self::Limiter,
            "ceiling" => Self::Ceiling,
            _ => return None,
        })
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub text: String,
    pub span: SourceSpan,
}
