[package]
name = "symphra-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
rayon.workspace = true
symphra-dsp.workspace = true
symphra-score.workspace = true
symphra-sampler.workspace = true
symphra-soundfont.workspace = true
symphra-vst3.workspace = true
